Repository modoboa/modoboa, pull requests merged in 2018-04, with the labels that each got.

#1441 fix python-ldap warnings on Python 2
  modoboa/lib/ldap_utils.py
Labels: enhancement

#1445 revert #1439 changes
  dev-requirements.txt
  setup.py
  test-requirements.txt
Labels: bug

#1446 prefer standard library version of mock over back port
  modoboa/admin/tests/test_api.py
  modoboa/admin/tests/test_domain.py
  modoboa/admin/tests/test_import_.py
  modoboa/admin/tests/test_mailbox_operations.py
  modoboa/admin/tests/test_mx.py
  modoboa/core/tests/test_authentication.py
  test-requirements.txt
Labels: enhancement, python3

#1447 ensure utf8 encoding is used when creating/accessing test database
  modoboa/test_settings.py
Labels: bug

#1463 Fix tox serve command
  .gitignore
  .travis.yml
  test-requirements.txt
  tox.ini
Labels: enhancement

#1464 PEP508 markers in requirements.txt have been broken since dfabe89
  setup.py
Labels: bug

#1462 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#1470 add missing optional dependency used by ckeditor for attaching images
  requirements.txt
Labels: bug
