Repository modoboa/modoboa, pull requests merged in 2022-10, with the labels that each got.

#2621 Added API key management to UI v2.
  frontend/locale/en/LC_MESSAGES/app.po
  frontend/locale/fr/LC_MESSAGES/app.po
  frontend/public/config.json
  frontend/src/api/account.js
  frontend/src/components/layout/Navbar.vue
  frontend/src/router/index.js
  frontend/src/views/user/APISetup.vue
  modoboa/core/api/v2/serializers.py
  modoboa/core/api/v2/tests.py
  modoboa/core/api/v2/viewsets.py
Labels: enhancement, new-ui

#2576 Mitigate spamhaus dns fail while querying for dnsbl
  modoboa/admin/management/commands/subcommands/_mx.py
  modoboa/admin/tests/test_mx.py
Labels: enhancement

#2622 Added missing migrations.
  doc/upgrade.rst
  modoboa/admin/apps.py
  modoboa/core/apps.py
  modoboa/core/commands/templates/settings.py.tpl
  modoboa/core/migrations/0023_auto_20221012_0911.py
  modoboa/dnstools/apps.py
  modoboa/limits/apps.py
  modoboa/maillog/apps.py
  modoboa/relaydomains/apps.py
  modoboa/transport/apps.py
  test_project/test_project/settings.py
Labels: bug

#2616 Show pending label when check is pending on GUIv2
  frontend/src/components/domains/DNSDetail.vue
Labels: enhancement, new-ui
