Repository modoboa/modoboa, pull requests merged in 2023-02, with the labels that each got.

#2767 Api throttling for rest framework
  doc/upgrade.rst
  frontend/src/App.vue
  frontend/src/api/repository.js
  frontend/src/views/Login.vue
  frontend/src/views/user/PasswordRecoveryChangeForm.vue
  frontend/src/views/user/PasswordRecoveryForm.vue
  frontend/src/views/user/PasswordRecoverySmsTotpForm.vue
  modoboa/admin/api/v1/viewsets.py
  modoboa/admin/api/v2/tests.py
  modoboa/admin/api/v2/viewsets.py
  modoboa/core/api/v1/viewsets.py
  modoboa/core/api/v2/views.py
  modoboa/core/api/v2/viewsets.py
  modoboa/core/commands/templates/settings.py.tpl
  modoboa/dnstools/api/v2/viewsets.py
  modoboa/lib/throttle.py
  modoboa/limits/api/v1/viewsets.py
  modoboa/maillog/api/v2/viewsets.py
  modoboa/parameters/api/v2/viewsets.py
  modoboa/relaydomains/api/v1/viewsets.py
  modoboa/transport/api/v2/viewsets.py
  test_project/test_project/settings.py
Labels: enhancement, security

#2780 Update frontend doc and fix new admin default url
  doc/rest_api.rst
  doc/upgrade.rst
  modoboa/core/commands/templates/settings.py.tpl
  modoboa/core/context_processors.py
  test_project/test_project/settings.py
Labels: enhancement, documentation

#2783 Do not export internal aliases
  modoboa/admin/management/commands/subcommands/_export.py
Labels: bug

#2796 log message on failed auth on api v2
  modoboa/core/api/v2/tests.py
  modoboa/core/api/v2/views.py
Labels: security

#2799 add SSHA password hasher
  modoboa/core/password_hashers/__init__.py
  modoboa/core/password_hashers/advanced.py
  modoboa/core/tests/test_authentication.py
Labels: enhancement

#2882 added core language migration
  modoboa/core/migrations/0024_alter_user_language.py
Labels: ready-to-merge

#2888 Added missing permissions on API endpoints
  modoboa/admin/api/v1/viewsets.py
  modoboa/core/api/v2/views.py
  modoboa/lib/permissions.py
  modoboa/parameters/api/v2/viewsets.py
Labels: bug, security

#2889 Fixed CSRF issues in edit operations.
  modoboa/admin/views/domain.py
  modoboa/admin/views/identity.py
Labels: bug, security

#2887 Make sure to reset creation forms between 2 uses.
  frontend/src/components/domains/DomainCreationForm.vue
  frontend/src/components/domains/DomainDNSForm.vue
  frontend/src/components/domains/DomainGeneralForm.vue
  frontend/src/components/domains/DomainLimitationsForm.vue
  frontend/src/components/domains/DomainOptionsForm.vue
  frontend/src/components/domains/DomainTransportForm.vue
  frontend/src/components/identities/AccountAliasForm.vue
  frontend/src/components/identities/AccountCreationForm.vue
  frontend/src/components/identities/AccountGeneralForm.vue
  frontend/src/components/identities/AccountMailboxForm.vue
  frontend/src/components/identities/AccountRoleForm.vue
  frontend/src/components/identities/AliasCreationForm.vue
  frontend/src/components/identities/AliasGeneralForm.vue
  frontend/src/components/identities/AliasRecipientForm.vue
  frontend/src/components/tools/CreationForm.vue
Labels: bug, new-ui
