Repository modoboa/modoboa, pull requests merged in 2023-07, with the labels that each got.

#3016 Tfa setup improvement
  docker/Dockerfile.dev
  frontend/package.json
  frontend/src/api/account.js
  frontend/src/components/user/TwoFactorAuthForm.vue
  frontend/src/plugins/vee-validate.js
  frontend/src/views/TwoFA.vue
  frontend/yarn.lock
  modoboa/core/api/v1/serializers.py
  modoboa/core/api/v1/viewsets.py
  modoboa/core/api/v2/tests.py
  modoboa/core/api/v2/viewsets.py
  modoboa/core/templates/core/user_security.html
  modoboa/core/tests/test_viewsets.py
  modoboa/static/js/twocols_nav.js
Labels: enhancement, security

#3026 Use asyncio from redis instead of aioredis to make app python 3.11 compatible
  .github/workflows/modoboa.yml
  modoboa/policyd/core.py
  modoboa/policyd/tests.py
  requirements.txt
  test-requirements.txt
Labels: python

#3017 Multiple frontend fix
  frontend/src/App.vue
  frontend/src/api/repository.js
  frontend/src/components/layout/Navbar.vue
  frontend/src/components/parameters/ParametersForm.vue
  frontend/src/views/TwoFA.vue
Labels: new-ui

#3012 Send only mailboxes
  doc/upgrade.rst
  docker-compose.yml
  frontend/src/components/identities/AccountCreationForm.vue
  frontend/src/components/identities/AccountForm.vue
  frontend/src/components/identities/AccountGeneralForm.vue
  frontend/src/components/identities/AccountMailboxForm.vue
  modoboa/admin/api/v1/serializers.py
  modoboa/admin/api/v2/serializers.py
  modoboa/admin/api/v2/tests.py
  modoboa/admin/forms/account.py
  modoboa/admin/handlers.py
  modoboa/admin/migrations/0021_mailbox_is_send_only.py
  modoboa/admin/models/mailbox.py
  modoboa/admin/templates/admin/mailform.html
  modoboa/core/commands/deploy.py
  modoboa/core/commands/templates/settings.py.tpl
  test_project/test_project/settings.py
Labels: enhancement
