Repository modoboa/modoboa, pull requests merged in 2023-10, with the labels that each got.

#3090 Fixed CSRF vulnerability on logout view
  modoboa/core/templatetags/core_tags.py
  modoboa/core/views/auth.py
  modoboa/lib/templatetags/lib_tags.py
  modoboa/static/css/custom.css
  modoboa/templates/common/menulist.html
  modoboa/templates/nlayout.html
Labels: bug, security

#3094 doc improvement
  doc/installation.rst
  doc/upgrade.rst
Labels: documentation

#3095 Fixed XSS vulnerability when displaying form error messages.
  modoboa/static/js/twocols_nav.js
  modoboa/templates/common/generic_field.html
Labels: bug, security

#3085 to avoid CSRF error due to multiple click
  modoboa/templates/registration/login.html
Labels: bug, enhancement
